name: MiniReader
options:
  bundleIdPrefix: com.yunhugy
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
targets:
  MiniReader:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: Sources/MiniReader
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: MiniReader
        CFBundleName: MiniReader
        CFBundleIdentifier: com.yunhugy.minireader
        CFBundleVersion: "1"
        CFBundleShortVersionString: "0.1.0"
        UILaunchScreen: {}
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.yunhugy.minireader
        GENERATE_INFOPLIST_FILE: false
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
